name: .NET Core CI
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Получаем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3
      # Шаг 2: Настройка .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'  
      # Шаг 3: Восстановление зависимостей проекта
      - name: Restore dependencies
        run: dotnet restore Lab2.Tests/Lab2.Tests.csproj
      # Шаг 4: Сборка проекта
      - name: Build project
        run: dotnet build Lab2.Tests/Lab2.Tests.csproj --configuration Release
      # Шаг 5: Запуск тестов
      - name: Run tests
        run: dotnet test Lab2.Tests/Lab2.Tests.csproj --configuration Release --no-build --verbosity normal
  
