name: .NET Core CI
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Получаем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3
      # Шаг 2: Настройка .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'  
      # Шаг 3: Восстановление зависимостей проекта
      - name: Restore dependencies
        run: dotnet restore TO2.sln
      # Шаг 4: Сборка проекта
      - name: Build project
        run: dotnet build --configuration Release
      # Шаг 5: Запуск тестов
      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal
  deploy:
    runs-on: ubuntu-latest
    needs: test 
    steps:
      # Шаг 1: Получаем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3
      # Шаг 2: Настройка SSH для развертывания 
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >~/.ssh/config <<EOF
          Host your-server
            HostName ${{ secrets.SERVER_HOST }}
            User ${{ secrets.SERVER_USER }}
            Port 22
            IdentityFile ~/.ssh/id_rsa
          EOF
      # Шаг 3: Развертывание на сервер 
      - name: Deploy to server
        run: |
          ssh your-server "cd /path/to/project && dotnet publish -c Release -o ./out && your-deployment-command"
